/**
* Site Configuration
* Generated by Netlify Function
* Last updated: 2025-10-21T18:21:44.991Z
*/

// contactInfo configuration
export const contactInfo = {
    agent: {
      name: "Lisa Hall",
      photo: "https://cdn.realtor.ca/individual/TS638762781600000000/highres/1250988.jpg",
      phone: "5199380155",
      email: "lisahall@mimmobilier.com",
      company: "M Immobilier",
      license: "REALTOR®",
      repo: "New-Listing-67",
      companyAddress: "147 Cartier Ave Suite # 400, Pointe-Claire, Quebec H9S 4R9",
      companyLogo: "https://www.leadingre.com/api/member-logo/911964E1-348C-4E42-9FA9-356186878191"
    },
    social: {
      instagram: "https://instagram.com/lisahallmontreal",
      facebook: "https://www.facebook.com/lisahallcourtier/",
      twitter: "https://twitter.com/executivehomesrealtyinc",
      linkedin: ""
    },
    email: "lisahall@mimmobilier.com",
    phone: "5199380155",
    address: "147 Cartier Ave Suite # 400, Pointe-Claire, Quebec H9S 4R9",
    hours: "Mon-Fri: 9am-5pm",
    mapLocation: {
      lat: 43.7,
      lng: -79.4
    },
    socialLinks: {
      instagram: "https://instagram.com/lisahallmontreal",
      facebook: "https://www.facebook.com/lisahallcourtier/",
      twitter: "https://twitter.com/executivehomesrealtyinc",
      linkedin: ""
    },
    agent2: null
  };

// galleryImages configuration
export const galleryImages = [
    {
      id: 1,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988149801-DJI_20250625151831_0268_D.jpg",
      alt: "Property image 1",
      category: "interior"
    },
    {
      id: 2,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988152447-DJI_20250625151841_0271_D.jpg",
      alt: "Property image 2",
      category: "kitchen"
    },
    {
      id: 3,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988154132-DJI_20250625151904_0276_D.jpg",
      alt: "Property image 3",
      category: "bedroom"
    },
    {
      id: 4,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988155363-DJI_20250625151918_0279_D.jpg",
      alt: "Property image 4",
      category: "bathroom"
    },
    {
      id: 5,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988156329-DJI_20250625151945_0282_D.jpg",
      alt: "Property image 5",
      category: "exterior"
    },
    {
      id: 6,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988157153-DJI_20250625152732_0298_D.jpg",
      alt: "Property image 6",
      category: "interior"
    },
    {
      id: 7,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988157900-DJI_20250625152738_0301_D.jpg",
      alt: "Property image 7",
      category: "kitchen"
    },
    {
      id: 8,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988158583-DJI_20250625152750_0307_D.jpg",
      alt: "Property image 8",
      category: "bedroom"
    },
    {
      id: 9,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988159337-DSC09090.jpg",
      alt: "Property image 9",
      category: "bathroom"
    },
    {
      id: 10,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988159826-DSC09091.jpg",
      alt: "Property image 10",
      category: "exterior"
    },
    {
      id: 11,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988160308-DSC09109.jpg",
      alt: "Property image 11",
      category: "interior"
    },
    {
      id: 12,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988160741-DSC09115.jpg",
      alt: "Property image 12",
      category: "kitchen"
    },
    {
      id: 13,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988161335-DSC09128.jpg",
      alt: "Property image 13",
      category: "bedroom"
    },
    {
      id: 14,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988161848-DSC09146.jpg",
      alt: "Property image 14",
      category: "bathroom"
    },
    {
      id: 15,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988162257-DSC09149.jpg",
      alt: "Property image 15",
      category: "exterior"
    },
    {
      id: 16,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988162667-DSC09160.jpg",
      alt: "Property image 16",
      category: "interior"
    },
    {
      id: 17,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988163048-DSC09171.jpg",
      alt: "Property image 17",
      category: "kitchen"
    },
    {
      id: 18,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988163475-DSC09174.jpg",
      alt: "Property image 18",
      category: "bedroom"
    },
    {
      id: 19,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988163907-DSC09194.jpg",
      alt: "Property image 19",
      category: "bathroom"
    },
    {
      id: 20,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988164304-DSC09197.jpg",
      alt: "Property image 20",
      category: "exterior"
    },
    {
      id: 21,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988164784-DSC09211.jpg",
      alt: "Property image 21",
      category: "interior"
    },
    {
      id: 22,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988165262-DSC09221.jpg",
      alt: "Property image 22",
      category: "kitchen"
    },
    {
      id: 23,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988165761-DSC09237.jpg",
      alt: "Property image 23",
      category: "bedroom"
    },
    {
      id: 24,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988166203-DSC09240.jpg",
      alt: "Property image 24",
      category: "bathroom"
    },
    {
      id: 25,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988166648-DSC09252.jpg",
      alt: "Property image 25",
      category: "exterior"
    },
    {
      id: 26,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988167109-DSC09255.jpg",
      alt: "Property image 26",
      category: "interior"
    },
    {
      id: 27,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988167526-DSC09271.jpg",
      alt: "Property image 27",
      category: "kitchen"
    },
    {
      id: 28,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988167928-DSC09274.jpg",
      alt: "Property image 28",
      category: "bedroom"
    },
    {
      id: 29,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988168407-DSC09284.jpg",
      alt: "Property image 29",
      category: "bathroom"
    },
    {
      id: 30,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988168905-DSC09287.jpg",
      alt: "Property image 30",
      category: "exterior"
    },
    {
      id: 31,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988169335-DSC09293.jpg",
      alt: "Property image 31",
      category: "interior"
    },
    {
      id: 32,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988169864-DSC09303.jpg",
      alt: "Property image 32",
      category: "kitchen"
    },
    {
      id: 33,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988170320-DSC09306.jpg",
      alt: "Property image 33",
      category: "bedroom"
    },
    {
      id: 34,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988170857-DSC09314.jpg",
      alt: "Property image 34",
      category: "bathroom"
    },
    {
      id: 35,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988171256-DSC09328.jpg",
      alt: "Property image 35",
      category: "exterior"
    },
    {
      id: 36,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988171680-DSC09336.jpg",
      alt: "Property image 36",
      category: "interior"
    },
    {
      id: 37,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988172107-DSC09350.jpg",
      alt: "Property image 37",
      category: "kitchen"
    },
    {
      id: 38,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988172515-DSC09356.jpg",
      alt: "Property image 38",
      category: "bedroom"
    },
    {
      id: 39,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988173037-DSC09373.jpg",
      alt: "Property image 39",
      category: "bathroom"
    },
    {
      id: 40,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988173559-DSC09380.jpg",
      alt: "Property image 40",
      category: "exterior"
    },
    {
      id: 41,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988173969-DSC09387.jpg",
      alt: "Property image 41",
      category: "interior"
    },
    {
      id: 42,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988174397-DSC09404.jpg",
      alt: "Property image 42",
      category: "kitchen"
    },
    {
      id: 43,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988174902-DSC09407.jpg",
      alt: "Property image 43",
      category: "bedroom"
    },
    {
      id: 44,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988175328-DSC09416.jpg",
      alt: "Property image 44",
      category: "bathroom"
    },
    {
      id: 45,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988175825-DSC09425.jpg",
      alt: "Property image 45",
      category: "exterior"
    },
    {
      id: 46,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988176463-DSC09434.jpg",
      alt: "Property image 46",
      category: "interior"
    },
    {
      id: 47,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988177276-DSC09437.jpg",
      alt: "Property image 47",
      category: "kitchen"
    },
    {
      id: 48,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988178170-DSC09440.jpg",
      alt: "Property image 48",
      category: "bedroom"
    },
    {
      id: 49,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988178857-DSC09443.jpg",
      alt: "Property image 49",
      category: "bathroom"
    },
    {
      id: 50,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988179821-DSC09446.jpg",
      alt: "Property image 50",
      category: "exterior"
    },
    {
      id: 51,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989529049-DJI_20250625151831_0268_D.jpg",
      alt: "Property image 51",
      category: "interior"
    },
    {
      id: 52,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989531765-DJI_20250625151841_0271_D.jpg",
      alt: "Property image 52",
      category: "kitchen"
    },
    {
      id: 53,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989533665-DJI_20250625151904_0276_D.jpg",
      alt: "Property image 53",
      category: "bedroom"
    },
    {
      id: 54,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989534976-DJI_20250625151918_0279_D.jpg",
      alt: "Property image 54",
      category: "bathroom"
    },
    {
      id: 55,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989535978-DJI_20250625151945_0282_D.jpg",
      alt: "Property image 55",
      category: "exterior"
    },
    {
      id: 56,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989536874-DJI_20250625152732_0298_D.jpg",
      alt: "Property image 56",
      category: "interior"
    },
    {
      id: 57,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989537903-DJI_20250625152738_0301_D.jpg",
      alt: "Property image 57",
      category: "kitchen"
    },
    {
      id: 58,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989540211-DJI_20250625152750_0307_D.jpg",
      alt: "Property image 58",
      category: "bedroom"
    },
    {
      id: 59,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989540955-DSC09090.jpg",
      alt: "Property image 59",
      category: "bathroom"
    },
    {
      id: 60,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989541727-DSC09091.jpg",
      alt: "Property image 60",
      category: "exterior"
    },
    {
      id: 61,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989542809-DSC09109.jpg",
      alt: "Property image 61",
      category: "interior"
    },
    {
      id: 62,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989543252-DSC09115.jpg",
      alt: "Property image 62",
      category: "kitchen"
    },
    {
      id: 63,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989543769-DSC09128.jpg",
      alt: "Property image 63",
      category: "bedroom"
    },
    {
      id: 64,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989544265-DSC09146.jpg",
      alt: "Property image 64",
      category: "bathroom"
    },
    {
      id: 65,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989544693-DSC09149.jpg",
      alt: "Property image 65",
      category: "exterior"
    },
    {
      id: 66,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989545209-DSC09160.jpg",
      alt: "Property image 66",
      category: "interior"
    },
    {
      id: 67,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989545652-DSC09171.jpg",
      alt: "Property image 67",
      category: "kitchen"
    },
    {
      id: 68,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989546101-DSC09174.jpg",
      alt: "Property image 68",
      category: "bedroom"
    },
    {
      id: 69,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989546547-DSC09194.jpg",
      alt: "Property image 69",
      category: "bathroom"
    },
    {
      id: 70,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989546946-DSC09197.jpg",
      alt: "Property image 70",
      category: "exterior"
    },
    {
      id: 71,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989547423-DSC09211.jpg",
      alt: "Property image 71",
      category: "interior"
    },
    {
      id: 72,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989547872-DSC09221.jpg",
      alt: "Property image 72",
      category: "kitchen"
    },
    {
      id: 73,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989548372-DSC09237.jpg",
      alt: "Property image 73",
      category: "bedroom"
    },
    {
      id: 74,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989548833-DSC09240.jpg",
      alt: "Property image 74",
      category: "bathroom"
    },
    {
      id: 75,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989549295-DSC09252.jpg",
      alt: "Property image 75",
      category: "exterior"
    },
    {
      id: 76,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989549780-DSC09255.jpg",
      alt: "Property image 76",
      category: "interior"
    },
    {
      id: 77,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989550208-DSC09271.jpg",
      alt: "Property image 77",
      category: "kitchen"
    },
    {
      id: 78,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989550615-DSC09274.jpg",
      alt: "Property image 78",
      category: "bedroom"
    },
    {
      id: 79,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989551102-DSC09284.jpg",
      alt: "Property image 79",
      category: "bathroom"
    },
    {
      id: 80,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989551604-DSC09287.jpg",
      alt: "Property image 80",
      category: "exterior"
    },
    {
      id: 81,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989552115-DSC09293.jpg",
      alt: "Property image 81",
      category: "interior"
    },
    {
      id: 82,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989552636-DSC09303.jpg",
      alt: "Property image 82",
      category: "kitchen"
    },
    {
      id: 83,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989553291-DSC09306.jpg",
      alt: "Property image 83",
      category: "bedroom"
    },
    {
      id: 84,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989553758-DSC09314.jpg",
      alt: "Property image 84",
      category: "bathroom"
    },
    {
      id: 85,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989554325-DSC09328.jpg",
      alt: "Property image 85",
      category: "exterior"
    },
    {
      id: 86,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989554747-DSC09336.jpg",
      alt: "Property image 86",
      category: "interior"
    },
    {
      id: 87,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989555188-DSC09350.jpg",
      alt: "Property image 87",
      category: "kitchen"
    },
    {
      id: 88,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989555580-DSC09356.jpg",
      alt: "Property image 88",
      category: "bedroom"
    },
    {
      id: 89,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989556138-DSC09373.jpg",
      alt: "Property image 89",
      category: "bathroom"
    },
    {
      id: 90,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989557004-DSC09380.jpg",
      alt: "Property image 90",
      category: "exterior"
    },
    {
      id: 91,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989557424-DSC09387.jpg",
      alt: "Property image 91",
      category: "interior"
    },
    {
      id: 92,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989558502-DSC09404.jpg",
      alt: "Property image 92",
      category: "kitchen"
    },
    {
      id: 93,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989559072-DSC09407.jpg",
      alt: "Property image 93",
      category: "bedroom"
    },
    {
      id: 94,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989559560-DSC09416.jpg",
      alt: "Property image 94",
      category: "bathroom"
    },
    {
      id: 95,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989560063-DSC09425.jpg",
      alt: "Property image 95",
      category: "exterior"
    },
    {
      id: 96,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989560890-DSC09434.jpg",
      alt: "Property image 96",
      category: "interior"
    },
    {
      id: 97,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989561875-DSC09437.jpg",
      alt: "Property image 97",
      category: "kitchen"
    },
    {
      id: 98,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989562821-DSC09440.jpg",
      alt: "Property image 98",
      category: "bedroom"
    },
    {
      id: 99,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989563503-DSC09443.jpg",
      alt: "Property image 99",
      category: "bathroom"
    },
    {
      id: 100,
      src: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760989564197-DSC09446.jpg",
      alt: "Property image 100",
      category: "exterior"
    }
  ];

// heroVideo configuration
export const heroVideo = {
    url: "https://www.youtube.com/shorts/ySLVz_ukizA",
    type: "video/mp4",
    autoplay: true,
    loop: true,
    muted: true,
    playsInline: true
  };

// homeShowcaseSections configuration
export const homeShowcaseSections = [
    {
      id: "section1",
      title: "4 Bedrooms",
      description: "The kitchen is something people love. The high ceilings is also something people love. The natural light and openness of the main floor, the combination of wood floors, open layout, and wall of windows creates an immediate sense of space and comfort.",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988149801-DJI_20250625151831_0268_D.jpg"
    },
    {
      id: "section2",
      title: "3.5 Bathrooms",
      description: "",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988152447-DJI_20250625151841_0271_D.jpg"
    },
    {
      id: "section3",
      title: "1981 SqFt",
      description: "Spacious living area with ample room for your lifestyle",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988154132-DJI_20250625151904_0276_D.jpg"
    },
    {
      id: "section4",
      title: "$$929,000",
      description: "",
      imageUrl: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988155363-DJI_20250625151918_0279_D.jpg"
    }
  ];

// neighborhood configuration
export const neighborhood = {
    name: "Sainte-Anne-de-Bellevue",
    city: "Sainte-Anne-de-Bellevue",
    description: "Sainte-Anne-de-Bellevue is a picturesque lakeside village on Montreal’s West Island, prized for its scenic canal boardwalks and marina views. The area combines family-friendly outdoor attractions like the Ecomuseum Zoo and Morgan Arboretum with a compact, walkable main street of cafés, local shops and lakeside dining.",
    highlights: [
      "Scenic Sainte-Anne-de-Bellevue Canal with boardwalk and marina views",
      "Ecomuseum Zoo – year-round outdoor wildlife park focused on Quebec species",
      "Morgan Arboretum – 605-acre conservation area with extensive trails",
      "Vibrant village atmosphere with farmers’ markets, charming shops and lakeside dining",
      "Historical 19th-century architecture and local cultural heritage"
    ]
  };

// neighborhoodAmenities configuration
export const neighborhoodAmenities = [
    {
      id: 1,
      name: "icyvibes",
      distance: "",
      category: "shopping",
      iconName: "ShoppingBag"
    },
    {
      id: 2,
      name: "Parc Dorset (Parc Wilkinson)",
      distance: "",
      category: "recreation",
      iconName: "Leaf"
    },
    {
      id: 3,
      name: "Ecomuseum Zoo",
      distance: "",
      category: "education",
      iconName: "School"
    },
    {
      id: 4,
      name: "Restaurant Le Khmer",
      distance: "",
      category: "dining",
      iconName: "Coffee"
    },
    {
      id: 5,
      name: "Morgan 44",
      distance: "",
      category: "dining",
      iconName: "Utensils"
    },
    {
      id: 6,
      name: "Gare Île-Perrot Quai 4",
      distance: "",
      category: "transportation",
      iconName: "Car"
    },
    {
      id: 7,
      name: "Lookout Point",
      distance: "",
      category: "recreation",
      iconName: "Users"
    },
    {
      id: 8,
      name: "Ceilidh Bar Restaurant",
      distance: "",
      category: "business",
      iconName: "Wifi"
    }
  ];

// neighborhoodStats configuration
export const neighborhoodStats = [
    {
      id: 1,
      title: "Walk Score",
      value: "20/100",
      caption: "Car-Dependent",
      iconName: "BadgeCheck",
      color: "bg-green-500"
    },
    {
      id: 2,
      title: "Transit Score",
      value: "65/100",
      caption: "Good Transit",
      iconName: "Compass",
      color: "bg-blue-500"
    },
    {
      id: 3,
      title: "Bike Score",
      value: "70/100",
      caption: "Good for Bikers",
      iconName: "Compass",
      color: "bg-blue-500"
    }
  ];

// openHouseDetails configuration
export const openHouseDetails = {
    nextDate: "Saturday, October 25, 2025",
    time: "2:00 PM - 4:00 PM",
    host: "Rebecca Matheson",
    phone: "5199380155",
    email: "rebecca@salesgenius.co",
    ctaText: "RSVP for Open House",
    virtualTourAvailable: false,
    virtualTourUrl: "",
    allOpenHouses: [
      {
        date: "Saturday, October 25, 2025",
        time: "2:00 PM - 4:00 PM"
      }
    ]
  };

// property configuration
export const property = {
    name: "603 Rue Frédéric-Back",
    address: {
      street: "603 Rue Frédéric-Back",
      city: "Sainte-Anne-de-Bellevue",
      state: "Quebec",
      zip: "H9X 0B7",
      country: "Canada"
    },
    price: "$929,000",
    beds: 4,
    baths: 3.5,
    sqft: 1981,
    lotSize: "30 x 120 ft",
    yearBuilt: 2010,
    type: "Condo Townhouse",
    status: "For Sale",
    description: "The open concept layout on the main floor is really functional for family life and there is separation with the bedrooms being on multiple floors for different family configurations. \n\nThe mezzanine-level primary suite with two walk-in closets, ensuite bathroom, and private balcony a rare feature that makes the home stand out.",
    shortDescription: "4 BEDS + 4 BATHS in Sainte-Anne-de-Bellevue",
    longDescription: "Multi-level layout with mezzanine, offering flexible living spaces. Bright open-concept main floor with large windows and double sliding doors for natural light. Private outdoor areas including a large terrace and balcony. Attached double garage with direct interior access. Proximity to future REM station and major highways for easy commuting. Brand new park was completed nearby, steps away. Walking distance to ECO museum and lots of walking paths.",
    mainFeatures: [],
    propertyType: "Condo Townhouse",
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988149801-DJI_20250625151831_0268_D.jpg",
    heroCaption: "Mezzanine Suite + Double Garage + Bright Open Concept = Your Perfect Family Townhome Just Listed!"
  };

// propertyFeatures configuration
export const propertyFeatures = [
    "The 3rd full bathroom as many of the homes in the area don't have this as well as the 4th full bedroom on the mezzanine. There is an opportunity for the new buyer to customize the light fixtures and make them their own.",
    "Offering more space, modern construction, strong features, and a desirable location. The 4th bedroom and the 3rd bathroom is a top selling feature as many other homes in the area do not have this."
  ];

// siteBranding configuration
export const siteBranding = {
    logoUrl: "https://www.leadingre.com/api/member-logo/911964E1-348C-4E42-9FA9-356186878191",
    logoAlt: "603 Rue Frédéric-Back",
    favicon: "/favicon.ico",
    colors: {
      primary: "#D9A566",
      primaryDark: "#8B6839",
      primaryLight: "#E6C38C",
      dark: "#111111",
      light: "#FFFFFF"
    },
    heroImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988149801-DJI_20250625151831_0268_D.jpg",
    footer: {
      copyrightText: "© 2024 603 Rue Frédéric-Back. All rights reserved.",
      disclaimer: "This website is for informational purposes only. Details are subject to change."
    },
    companyName: "M Immobilier",
    companyLogo: "https://www.leadingre.com/api/member-logo/911964E1-348C-4E42-9FA9-356186878191",
    accentColor: "#D9A566",
    footerText: "© 2024 603 Rue Frédéric-Back. All rights reserved."
  };

// siteMetadata configuration
export const siteMetadata = {
    title: "603 Rue Frédéric-Back | Condo Townhouse | Sainte-Anne-de-Bellevue",
    description: "Mezzanine Suite + Double Garage + Bright Open Concept = Your Perfect Family Townhome Just Listed!",
    keywords: "condo townhouse, Sainte-Anne-de-Bellevue real estate, 4 bedroom, 3.5 bathroom, $929,000",
    ogImage: "https://salesgenius.s3.ca-central-1.amazonaws.com/uploads/1760988149801-DJI_20250625151831_0268_D.jpg",
    ogType: "website",
    twitterCard: "summary_large_image",
    canonical: "https://603ruefrédéric-back.com"
  };

// testimonials configuration
export const testimonials = [
    {
      id: 1,
      name: "David Chen",
      role: "Recent Homebuyer",
      content: "Rebecca Matheson provided exceptional service and found us exactly what we were looking for in Sainte-Anne-de-Bellevue.",
      avatar: "https://randomuser.me/api/portraits/men/22.jpg"
    },
    {
      id: 2,
      name: "Jennifer Liu",
      role: "Interior Designer",
      content: "The attention to detail and quality of finishes in this property is outstanding. Rebecca Matheson presented every detail clearly.",
      avatar: "https://randomuser.me/api/portraits/women/44.jpg"
    },
    {
      id: 3,
      name: "Mark Williams",
      role: "Neighborhood Resident",
      content: "Living in this area, you appreciate the convenience and lifestyle. Rebecca Matheson knows the market incredibly well.",
      avatar: "https://randomuser.me/api/portraits/men/35.jpg"
    }
  ];

